import queue #standard libray--contains classes for creating and managing different types of queues

#model the specific problem --
# models the problem's structure and rules
class TransportProblem:
    # 1. state representation -- how states are represented (int 1 to N)
    def __init__(self, N):  #--init-- is special method, automatically called when create a new object from class
        self.N = N

    # 2. Start state -- where the problem begins
    def start_state(self):
        return 1

    # 3. Goal state -- the target condition (goal_state(), goal_test())
    def goal_state(self):
        return self.N

    def goal_test(self, state):
        return state == self.goal_state()

    # 4. Successors and costs -- how the next states are generated and the associated costs
    def SuccAndCost(self, state):
        result = []
        if state + 1 <= self.N:
            result.append(('walk', state+1, 1))
        if state*2 <= self.N:
            result.append(('tram', state*2, 2))
        return result

#generic search algorith
def uniformCostSearch(problem):
    # declare priority queue
    frontier = queue.PriorityQueue()  #stores nodes to be explored (cumulative cost, state, solution path)
    frontier.put((0, problem.start_state(), list()))  # initialize cost, startstate and path
    # start the search loop
    while True:  #infinite loop until it finds goal state
        # cumulative cost to reach current state, current stat being explored, list of actions taken to reach this state
        pastCost, state, solution = frontier.get()  #retrieves node with lowest cumulative cost
        if problem.goal_test(state): #if current state is goal state
            return (pastCost, solution) # return tuple with cost of solution path & list of actions
        # put out on the frontier
        # generate successors
        # for each successor of current state (generated by problem.SuccAndCost(state))
        for action, newState, cost in problem.SuccAndCost(state):
            # successor state is added to the frontier with
            # updated cumulative cost => pastCost + cost
            # updated state => newState
            # updated solution path => solution + [action]
            frontier.put((pastCost+cost, newState, solution+[action]))

# Depth-First Search
def depthFirstSearch(problem):
    frontier = []  # frontier stack LIFO
    frontier.append((0, problem.start_state(), list()))  #cost, state, path
    while frontier:
        pastCost, state, solution = frontier.pop()
        if problem.goal_test(state):
            return (pastCost, solution)
        for action, newState, cost in problem.SuccAndCost(state):
            frontier.append((pastCost+cost, newState, solution+[action]))

# Breadth-First Search
def breadthFirstSearch(problem):
    frontier = queue.Queue()  #FIFO
    frontier.put((0, problem.start_state(), list())) #initialize cost, state, path
    while not frontier.empty():
        pastCost, state, solution = frontier.get()  #takes node from frontier to expand
        if problem.goal_test(state): #check node if it is goal state
            return (pastCost, solution)
        for action, newState, cost in problem.SuccAndCost(state): #generate Successor
            frontier.put((pastCost+cost, newState, solution+[action])) #store new node in the frontier with values associated

# takes paramter solution
# parameter expected to be tuple containing total cost and sequence of actions
def printSolution(solution, algorithm):
    totalCost, history = solution  # unpack the tuple and store them into respective variables
    print(f"\n{algorithm}\n========================")
    print("totalCost: {}".format(totalCost))  #{} placeholder inster value of totalCost
    for item in history:
        print(item)
    print("***************************")
    
problem = TransportProblem(40)
#print(problem.SuccAndCost(3))
#print(problem.SuccAndCost(9))
printSolution(uniformCostSearch(problem), "Uniform Cost Search")
printSolution(depthFirstSearch(problem), "Depth First Search")
printSolution(breadthFirstSearch(problem), "Breadth First Search")